config/routes.rb
Eskvalleytales::Application.routes.draw do
  match '/' => 'users#index'

  match 'user/:login' => 'user#show'
  match 'user/:search' => 'user#search'
  resource :sessions
  match 'session/:destroy' => 'sessions#destroy'
  resources :comments
  resources :users
  resources :subcomments

  resources :users do  
      resources :comments do
         resources  :subcomments
     end
  end

  resources :comments do  
      resources :subcomments
  end

  resources :users do
        resources :emails
  end

  resources :userss do  
      resources :fiendships
  end

  resources :users do  
      resources :subcomments
  end

  match '/:controller(/:action(/:id))'
end

app/models/subcomment.rb
class Subcomment < ActiveRecord::Base
belongs_to  :user
belongs_to  :comment

end

app/controllers/subcomments_controller.rb
class SubcommentsController < ApplicationController
  # GET /subcomments
  # GET /subcomments.xml
  def index
    @subcomments = Subcomment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subcomments }
    end
  end

  # GET /subcomments/1
  # GET /subcomments/1.xml
  def show
    @subcomment = Subcomment.find(params[:id])
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subcomment }
    end
  end

  # GET /subcomments/new
  # GET /subcomments/new.xml
  def new
    @subcomment = Subcomment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subcomment }
    end
  end

  # GET /subcomments/1/edit
  def edit
    @subcomment = Subcomment.find(params[:id])
  end

  # POST /subcomments
  # POST /subcomments.xml

  def create
    @cuser = @current_user    
    @comment = Comment.find(params[:comment_id])
    @user = User.find(params[@comment.user_id]) 
    @comment.subcomments.create( :commenter => @cuser.login, :user => @user.id, :body => params[:subcomment][:body])
    respond_to do |format|
     format.js  
     format.html {redirect_to user_path} 
    end    
  end

  # PUT /subcomments/1
  # PUT /subcomments/1.xml
  def update
    @subcomment = Subcomment.find(params[:id])

    respond_to do |format|
      if @subcomment.update_attributes(params[:subcomment])
        format.html { redirect_to(@subcomment, :notice => 'Subcomment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subcomment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subcomments/1
  # DELETE /subcomments/1.xml
  def destroy
    @subcomment = Subcomment.find(params[:id])
    @subcomment.destroy

    respond_to do |format|
      format.html { redirect_to(subcomments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/subcomments_helper.rb
module SubcommentsHelper
end

app/views/subcomments/_form.html.erb
<%= form_for(@subcomment) do |f| %>
  <% if @subcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcomment.errors.count, "error") %> prohibited this subcomment from being saved:</h2>

      <ul>
      <% @subcomment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_area :commenter %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br />
    <%= f.text_field :comment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcomments/_subcomform.html.erb
      <% comment.subcomments.each do |subcomment| %>
         <div id="subremark" >
           <p><%= subcomment.body %></p>
         <div id="commenter" >
          <p><%= subcomment.commenter %></p>
         </div>
         </div>
        
        
          <%= form_for [comment, Subcomment.new],:remote => true do |form| %>
            <div id="body">
              <%= form.text_field :body %>
            </div>                   
            <%= form.submit %>           
          <% end %>
      <% end %>

app/views/subcomments/_subcomment.html.erb
<% @comment = Comment.find(params[:comment_id]) %>
<% @user.comments.each do |comment| %>
          <div id = "remark" ><p><%= comment.body %>
          <div id = "commenter" ><%= comment.commenter %></p> 
          </div> 
          </div>   

  <% comment.subcomments.each do |subcomment| %>
            <div id = "subremark" ><p><%= subcomment.body %></p>          
            <div id = "commenter" ><p><%= subcomment.comment_id %></p>
            </div>
            </div>
  <% end %>
<% end %>

app/views/subcomments/_subform.html.erb
<%= form_for [Comment, index, Subcomment.new],:remote => true do |form| %>

   <div id="body">
      <%= form.text_field :body %>
   </div>           
      <% form.hidden_field :comment_id,  :value => 1 %>         
   <p>
      <%= form.submit %> 
   </p>
<% end %>

app/views/subcomments/create.js.erb
<% Rails.logger.debug "!!! the value of @user is '#{@user.inspect}' with the class of  '#{@user.class.name}'" -%>
$('#subcomremark').html('<%= escape_javascript(render(:partial => "subcomments/subcomment",  :object => @user )) %>');

app/views/subcomments/edit.html.erb
<h1>Editing subcomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcomment %> |
<%= link_to 'Back', subcomments_path %>

app/views/subcomments/index.html.erb
<h1>Listing subcomments</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Commenter</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcomments.each do |subcomment| %>
  <tr>
    <td><%= subcomment.body %></td>
    <td><%= subcomment.commenter %></td>
    <td><%= subcomment.comment_id %></td>
    <td><%= link_to 'Show', subcomment %></td>
    <td><%= link_to 'Edit', edit_subcomment_path(subcomment) %></td>
    <td><%= link_to 'Destroy', subcomment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcomment', new_subcomment_path %>

app/views/subcomments/new.html.erb
<h1>New subcomment</h1>

<%= render 'form' %>

<%= link_to 'Back', subcomments_path %>

app/views/subcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @subcomment.body %>
</p>

<p>
  <b>Commenter:</b>
  <%= @subcomment.commenter %>
</p>

<p>
  <b>Comment:</b>
  <%= @subcomment.comment_id %>
</p>


<%= link_to 'Edit', edit_subcomment_path(@subcomment) %> |
<%= link_to 'Back', subcomments_path %>